services:
  server:
    build: ./server        
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: