# Generated by Django 5.1 on 2024-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pagerank_value',
            field=models.FloatField(default=0.0),
        ),
    ]
